### PR TITLE
Multi-line comments!

### PR DESCRIPTION
**Pull request by plastpappa**
Added multi-line comment support. Syntax is "#:" and ":#".

### CODE REVIEW

**Comment by towerofnix** [comment]
Indent still isn't perfect but I'll fix it :package:

**Comment by joker314** [comment]
Now that this is merged, the README should probably be modified too?

> [Multi-line comment syntax has not been decided on yet.](#)

**Comment by towerofnix** [comment]
@joker314 Yeah, but this project is pretty much concluded. I guess you should always keep documentation updated, but I don't know if it's worth it here.

For what it's relevant, if we were keeping the README updated, we'd also want to get rid of the stuff about `--harmony` node.js flags - those are all in the past and no longer necessary.

**Comment by plastpappa** [comment]
> @joker314 Yeah, but this project is pretty much concluded. I guess you should always keep documentation updated, but I don't know if it's worth it here.

What do you mean? My indie startup software company uses this language and its documentation daily to run the backend of our site (it's crafted with <3).

**Comment by joker314** [comment]
This reminds me -- you may wish to add a licence so that what @kvackkvack is doing isn't considered copyright infringement; and so people can continue development in a fork.

**Comment by towerofnix** [comment]
I cannot tell if any of you are being serious.

**Comment by plastpappa** [comment]
I'm very much not. Not sure why @joker314 is giving this so much attention all of a sudden, though.

**Comment by joker314** [comment]
The latter clause of my sentence was serious--the AST builder looked cool

**Comment by towerofnix** [comment]
No worries, I wasn't being serious when I said I couldn't tell if any of you were being serious. I seriously could tell you weren't seriously being serious.

**Comment by bates64** [comment]
I'm surprised any of you guys still exist. Also, "over 2 years ago"? wow

**Comment by plastpappa** [comment]
> I'm surprised any of you guys still exist. Also, "over 2 years ago"? wow

I'm surprised you still exist! Makes it like 2.5 years ago at this point. Scary to think about.

**Comment by towerofnix** [comment]
Of course we all still exist! :tada:

What was the first project we really all worked together on? OpenSprites? I think that's older than this.

**Comment by plastpappa** [comment]
> What was the first project we really all worked together on? OpenSprites? I think that's older than this.

I wasn't around for that I don't think. I'm pretty sure I somehow met Alex and he got me to join that JS game library thing? Sprint, I think?

**Comment by bates64** [comment]
Yep, it was Sprint.

@kvackkvack do you have Discord or something Florrie and I can catch up with you on? Github isn't the best place 😉

**Comment by kvackkvack** [comment]
Yeah, actually - try @arthur#5711

**Pull request merged**
